name: Execute Python Script

on:
  push:
    branches:
      - main  # Le script s'exécute lorsque tu fais un push sur la branche principale

jobs:
  run-script:
    runs-on: ubuntu-latest  # Exécution sur un environnement Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Utilise Python 3.8

    - name: Install dependencies
      run: |
        pip install requests  # Installe la bibliothèque 'requests'

    - name: Run main.py
      run: |
        python main.py  # Exécute ton script Python

