name: Exécution du script Python

on:
  push:
    branches:
      - main  # S'exécute uniquement sur la branche principale

jobs:
  run-script:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Vérifie que le dépôt est bien téléchargé

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Choisis la version de Python que tu utilises

      - name: Install dependencies
        run: |
          pip install requests  # Installe la bibliothèque requests pour télécharger les playlists

      - name: Run the Python script
        run: |
          python main.py  # Exécute ton script Python
